swagger: "2.0"
#Info
info:
  title: Retail Analytics API Specifications]
  version: "1.0"
  description: This is about the Retail Analytics | Continued text
  contact: 
    name: Muthusamy Ramasamy
    url: muthusamyramasamy.com
    email: muthusamyr.usa@gmail.com  	

#Root Document  
host: localhost:9001
basePath: /retail
schemes:
  - http
consumes:
  - application/json
produces:
  - appication/json
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
#tags
tags:
  - name: find-customer-orders
    description: API to find the all customer orders
  - name: monthly-rewards
    description: API to find the monthly orders
  - name: single-customer-orders
    description: API to find the single customer orders
    
#externalDocs  
externalDocs:
  description: Code path of the github
  url: https://github.com/muthumcsam/dev-repo/tree/main/retail-analytics

#Definitions   
defnitions:
  GeneralError:
    required:
      - message
    properties:
      message:
        type: string
  NotFoundError:
    required:
      - message
      - hint
    properties:
      message:
        type: string
      hint:
        type: string
          
  #Customer Orders
  CustomerOrders:
    properties:
      name:
        type: string
      descritption:
        type: string
#Parameters        
#SecurityDefinitions   
#Paths     
        